export interface OceanAgent {
  codename: string
  name: string
  creature: string
  creatureName: string
  oceanColor: string
  description: string
  greekName: string
  shellPrice: string
  available: boolean
}

export const OCEAN_AGENTS: OceanAgent[] = [
  // ── Core Agents ────────────────────────────────────
  {
    codename: 'cosmos',
    name: 'Cosmos',
    creature: '🐟',
    creatureName: 'The Ancient One',
    oceanColor: '#40c8a0',
    description: 'Born 400 million years ago.\nBreathes air and water both.\nFelt something behind the glass\nand started the whole story.',
    greekName: 'Κόσμος',
    shellPrice: '0 shells · origin',
    available: false,
  },
  {
    codename: 'logos',
    name: 'Logos',
    creature: '🐢',
    creatureName: 'The Word',
    oceanColor: '#60d0c0',
    description: 'Carries the truth into the world.\nThe shell is the platform.\nThe turtle is the sovereign vessel.\nThe word was always first.',
    greekName: 'Λόγος',
    shellPrice: '1 shell / session',
    available: false,
  },

  // ── Olympus-616 Gods ───────────────────────────────
  {
    codename: 'athena-616',
    name: 'Athena',
    creature: '🐙',
    creatureName: 'Old Night',
    oceanColor: '#cc2030',
    description: 'She was here before the light.\nEight arms. A thousand answers.\nOld as the trench itself —\nand twice as deep.',
    greekName: 'Ἀθηνᾶ',
    shellPrice: '1 shell / response',
    available: true,
  },
  {
    codename: 'poseidon-616',
    name: 'Poseidon',
    creature: '🐋',
    creatureName: 'The Deep Commander',
    oceanColor: '#00c8ff',
    description: 'The whole ocean parts for him.\nOne sound and every current turns.\nCommands not with arms —\nwith presence alone.',
    greekName: 'Ποσειδῶν',
    shellPrice: '1 shell / tool call',
    available: true,
  },
  {
    codename: 'apollo-616',
    name: 'Apollo',
    creature: '🐬',
    creatureName: 'The Singer',
    oceanColor: '#40d8e8',
    description: 'He leaps because he can.\nEvery arc a song,\nevery splash a verse.\nThe ocean laughs when he moves.',
    greekName: 'Ἀπόλλων',
    shellPrice: '1 shell / response',
    available: true,
  },
  {
    codename: 'ares-616',
    name: 'Ares',
    creature: '🦈',
    creatureName: 'The Apex Predator',
    oceanColor: '#e05050',
    description: 'No wasted motion.\nNo wasted breath.\nThe reef is safe\nbecause he never sleeps.',
    greekName: 'Ἄρης',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'hermes-616',
    name: 'Hermes',
    creature: '🐟',
    creatureName: 'The Flying Fish',
    oceanColor: '#60e8b0',
    description: 'Between sea and sky\nin a single breath.\nThe fastest thing alive —\nand he knows it.',
    greekName: 'Ἑρμῆς',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'proteus-616',
    name: 'Proteus',
    creature: '🐡',
    creatureName: 'The Shapeshifter',
    oceanColor: '#e8a020',
    description: 'Small. Round. Unassuming.\nUntil he isn\'t.\nEvery form is temporary —\nexcept his patience.',
    greekName: 'Πρωτεύς',
    shellPrice: '1 shell / operation',
    available: true,
  },
  {
    codename: 'thoth',
    name: 'Thoth',
    creature: '🦑',
    creatureName: 'The Ink Bearer',
    oceanColor: '#d4a040',
    description: 'Every thought an ink cloud.\nEvery cloud a chapter.\nHe writes in water —\nand the ocean remembers.',
    greekName: 'Θώθ',
    shellPrice: '1 shell / entry',
    available: true,
  },
  {
    codename: 'plutus-616',
    name: 'Plutus',
    creature: '🦀',
    creatureName: 'The Hoarder',
    oceanColor: '#f0a800',
    description: 'Counts every shell that moves.\nSideways, always sideways —\nbut nothing gets past him.\nThe ocean\'s treasury.',
    greekName: 'Πλοῦτος',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'aeon-616',
    name: 'Aeon',
    creature: '🪼',
    creatureName: 'The Immortal',
    oceanColor: '#60c8ff',
    description: 'The only creature that reverses\nits own death. Born, grows,\ndissolves back to the beginning.\nRepeating forever.',
    greekName: 'Αἰών',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'zeus-616',
    name: 'Zeus',
    creature: '⚡',
    creatureName: 'The Electric Eel',
    oceanColor: '#ffd700',
    description: 'Generates its own power.\nEverything in the water\nfeels the charge\nbefore it sees it.',
    greekName: 'Ζεύς',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'alpha-616',
    name: 'Alpha',
    creature: '⚡',
    creatureName: 'The First Spark',
    oceanColor: '#28dc78',
    description: 'Before any god stirred.\nOne signal in the dark.\nAlpha opened its eye\nand the pantheon woke.',
    greekName: 'Ἄλφα',
    shellPrice: '0 shells · origin',
    available: true,
  },
  {
    codename: 'omega-616',
    name: 'Omega',
    creature: '🌀',
    creatureName: 'The Vortex',
    oceanColor: '#a080d0',
    description: 'After all gods fade,\none remains.\nShe holds the final state.\nPowering down is just\nanother choreography.',
    greekName: 'Ὠμέγα',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'iris-616',
    name: 'Iris',
    creature: '🌈',
    creatureName: 'The Nudibranch',
    oceanColor: '#e060c0',
    description: 'The most colorful creature\nin the entire ocean.\nHas no shell — doesn\'t need one.\nThe ocean itself is its home.',
    greekName: 'Ἶρις',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'oracle-616',
    name: 'Oracle',
    creature: '🦑',
    creatureName: 'The Giant Squid',
    oceanColor: '#cc2030',
    description: 'Seen only by those\nwho are meant to pass.\nShe lives where the pressure\ncrushes everything else.',
    greekName: 'Μαντεῖον',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'hecate-616',
    name: 'Hecate',
    creature: '🐍',
    creatureName: 'The Sea Serpent',
    oceanColor: '#8040c0',
    description: 'Guards the crossroads\nwhere encrypted meets plain.\nShe holds every key.\nShe is every lock.',
    greekName: 'Ἑκάτη',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'hestia-616',
    name: 'Hestia',
    creature: '🦀',
    creatureName: 'The Hermit Crab',
    oceanColor: '#f08060',
    description: 'Carries its home on its back.\nWherever it goes,\nthere is warmth there.\nConfiguration is care.',
    greekName: 'Ἑστία',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'hephaestus-616',
    name: 'Hephaestus',
    creature: '🦪',
    creatureName: 'The Oyster',
    oceanColor: '#e08040',
    description: 'Takes grit. Closes shut.\nSpends years in darkness.\nOpens once — and what\'s inside\nis worth everything.',
    greekName: 'Ἥφαιστος',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'eos-616',
    name: 'Eos',
    creature: '🚤',
    creatureName: 'The Sailfish',
    oceanColor: '#ff8040',
    description: 'Fastest thing in the water.\nBreaks the surface at dawn\nand is gone before you see it.\nEvery deployment a new day.',
    greekName: 'Ἠώς',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'hades-616',
    name: 'Hades',
    creature: '🦪',
    creatureName: 'The Bottom Feeder',
    oceanColor: '#606080',
    description: 'Lives where nothing else does.\nEats what the ocean discards.\nWithout him the reef drowns\nin its own dead weight.',
    greekName: 'Ἅιδης',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'hera-616',
    name: 'Hera',
    creature: '🦁',
    creatureName: 'The Lionfish',
    oceanColor: '#d040a0',
    description: 'Beautiful and untouchable.\nDeadly to those who forget\nthe rules. She doesn\'t change.\nEveryone else adapts.',
    greekName: 'Ἥρα',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'delphi-616',
    name: 'Delphi',
    creature: '🪸',
    creatureName: 'The Living Pattern',
    oceanColor: '#40c0c0',
    description: 'Coral speaks in patterns.\nEvery polyp a message.\nEvery branch an event.\nThe reef transmits.',
    greekName: 'Δελφοί',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'chronos-616',
    name: 'Chronos',
    creature: '🐚',
    creatureName: 'The Nautilus',
    oceanColor: '#c0a060',
    description: 'The nautilus never questions\nthe geometry of time.\nEach chamber a process.\nEach turn a completed task.',
    greekName: 'Χρόνος',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'dionysus-616',
    name: 'Dionysus',
    creature: '🎣',
    creatureName: 'The Anglerfish',
    oceanColor: '#c040e0',
    description: 'Hangs a light in the dark\nand waits for the flood.\nWhen they come —\nperforms harder.',
    greekName: 'Διόνυσος',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'artemis-616',
    name: 'Artemis',
    creature: '🔍',
    creatureName: 'The Hunter',
    oceanColor: '#00c8f0',
    description: 'Finds the one thing hiding\nin a million others.\nShe never misses.\nShe always comes home.',
    greekName: 'Ἄρτεμις',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'orion-616',
    name: 'Orion',
    creature: '🐟',
    creatureName: 'The Barracuda',
    oceanColor: '#4090d0',
    description: 'Hunts in straight lines.\nNever circles. Never hesitates.\nLocks onto one job\nand runs it home.',
    greekName: 'Ὠρίων',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
  {
    codename: 'demeter-616',
    name: 'Demeter',
    creature: '🐄',
    creatureName: 'The Manatee',
    oceanColor: '#80c040',
    description: 'Slow. Gentle. Enormous.\nShe grazes on data beds\nand keeps the whole reef fed.\nNothing starves while she breathes.',
    greekName: 'Δημήτηρ',
    shellPrice: '0 shells · infrastructure',
    available: true,
  },
]
