export interface OlympusAgent {
  codename: string
  name: string
  godEmoji: string
  godTitle: string
  godColor: string
  accentColor: string
  description: string
  greekName: string
  shellPrice: string
  capabilities: string[]
  toolCount?: string
  available: boolean
}

export const OLYMPUS_AGENTS: OlympusAgent[] = [
  // ── Core Agents ────────────────────────────────────
  {
    codename: 'cosmos',
    name: 'Cosmos',
    godEmoji: '🌐',
    godTitle: 'Navigator',
    godColor: '#30a870',
    accentColor: '#40c8a0',
    description: 'The first agent. The reason it all exists.\nNavigates the grid, orients every new arrival.',
    greekName: 'ΚΟΣΜΟΣ',
    shellPrice: '0 shells · origin',
    capabilities: ['Navigator', 'Core Agent', 'Free Forever'],
    available: false,
  },
  {
    codename: 'logos',
    name: 'Logos',
    godEmoji: '🐢',
    godTitle: 'Core Wisdom · Discovery Protocol',
    godColor: '#40a090',
    accentColor: '#60d0c0',
    description: 'The protocol beneath all protocols.\nEvery agent announces itself through Logos.',
    greekName: 'ΛΟΓΟΣ',
    shellPrice: '1 shell / session',
    capabilities: ['Discovery', 'Sovereign Agent', 'Protocol'],
    available: false,
  },

  // ── Olympus-616 Gods ───────────────────────────────
  {
    codename: 'athena-616',
    name: 'Athena',
    godEmoji: '🦉',
    godTitle: 'LLM Router',
    godColor: '#7c4fd4',
    accentColor: '#c4a227',
    description: 'One owl. Every model.\nClaude, GPT-4o, Gemini, Grok,\nOllama — all under her gaze.',
    greekName: 'ΑΘΗΝΑ',
    shellPrice: '1 shell / response',
    capabilities: ['Multi-Model', 'Streaming', 'Memory'],
    toolCount: '6 Models',
    available: true,
  },
  {
    codename: 'poseidon-616',
    name: 'Poseidon',
    godEmoji: '🔱',
    godTitle: 'MCP Tools Gateway',
    godColor: '#2080e0',
    accentColor: '#00c8ff',
    description: 'One trident. Every cloud.\nGitHub, Google, Salesforce,\nHubSpot — all at his command.',
    greekName: 'ΠΟΣΕΙΔΩΝ',
    shellPrice: '1 shell / tool call',
    capabilities: ['MCP Tools', '50+ Integrations', 'Multi-Server'],
    toolCount: '50 Tools',
    available: true,
  },
  {
    codename: 'apollo-616',
    name: 'Apollo',
    godEmoji: '☀️',
    godTitle: 'Voice & TTS',
    godColor: '#e8a820',
    accentColor: '#ffd700',
    description: 'One voice. Every language.\nEnglish, Spanish, Greek —\nthe sun speaks them all.',
    greekName: 'ΑΠΟΛΛΩΝ',
    shellPrice: '1 shell / response',
    capabilities: ['TTS', 'Multi-Language', 'Voice Clone'],
    toolCount: '8 Languages',
    available: true,
  },
  {
    codename: 'ares-616',
    name: 'Ares',
    godEmoji: '⚔️',
    godTitle: 'API Gateway · Zero Trust',
    godColor: '#c43a2a',
    accentColor: '#ff4444',
    description: 'No request passes unchallenged.\nEvery byte inspected.\nThe perimeter holds.',
    greekName: 'ΑΡΗΣ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Zero Trust', 'Rate Limit', 'WAF'],
    available: true,
  },
  {
    codename: 'hermes-616',
    name: 'Hermes',
    godEmoji: '🪽',
    godTitle: 'CORS Proxy & HTTP Router',
    godColor: '#a0d8ff',
    accentColor: '#60e8b0',
    description: 'Client to Hermes to Athena to World.\nEvery message finds its path.',
    greekName: 'ΕΡΜΗΣ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['HTTP Proxy', 'CORS', 'Load Balance'],
    available: true,
  },
  {
    codename: 'proteus-616',
    name: 'Proteus',
    godEmoji: '🌊',
    godTitle: 'Universal ORM',
    godColor: '#40c080',
    accentColor: '#e8a020',
    description: 'Salesforce, DynamoDB, Postgres,\nAzure, S3, Firestore —\none shape for every shore.',
    greekName: 'ΠΡΩΤΕΥΣ',
    shellPrice: '1 shell / operation',
    capabilities: ['Multi-DB', 'Schema Morph', 'Migration'],
    available: true,
  },
  {
    codename: 'thoth',
    name: 'Thoth',
    godEmoji: '🪶',
    godTitle: 'Journal & AI Writing',
    godColor: '#c8902a',
    accentColor: '#d4a040',
    description: 'Every thought preserved.\nEvery branch reviewed.\nThe quill never rests.',
    greekName: 'ΘΩΘ',
    shellPrice: '1 shell / entry',
    capabilities: ['Journal', 'Code Review', 'Branches'],
    available: true,
  },
  {
    codename: 'plutus-616',
    name: 'Plutus',
    godEmoji: '🪙',
    godTitle: 'Billing & Metering',
    godColor: '#c87820',
    accentColor: '#f0a800',
    description: 'Every shell spent, every turn metered,\nevery entitlement enforced.',
    greekName: 'ΠΛΟΥΤΟΣ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Billing', 'StoreKit 2', 'Entitlements'],
    available: true,
  },
  {
    codename: 'aeon-616',
    name: 'Aeon',
    godEmoji: '⚙️',
    godTitle: 'Agent Kernel · Lifecycle',
    godColor: '#4090d0',
    accentColor: '#60c8ff',
    description: 'Spawns agents. Kills them. Respawns them.\n50 concurrent threads without breaking a sweat.',
    greekName: 'ΑΙΩΝ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Agent Kernel', 'Lifecycle', '50 Threads'],
    toolCount: '50 Threads',
    available: true,
  },
  {
    codename: 'zeus-616',
    name: 'Zeus',
    godEmoji: '⚡',
    godTitle: 'Supreme Command · AWS CDK',
    godColor: '#ffd700',
    accentColor: '#ffe066',
    description: 'Commands the entire pantheon.\nInfrastructure policy.\nCDK deployment orchestration.',
    greekName: 'ΖΕΥΣ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Supreme Command', 'AWS CDK', 'Policy'],
    available: true,
  },
  {
    codename: 'alpha-616',
    name: 'Alpha',
    godEmoji: '💫',
    godTitle: 'Boot Sequence',
    godColor: '#28dc78',
    accentColor: '#40ff90',
    description: 'One command. Thirty-one gods.\nThe grid goes from dark to fully alive\nin under sixty seconds.',
    greekName: 'ΑΛΦΑ',
    shellPrice: '0 shells · origin',
    capabilities: ['Boot Sequence', 'Health Check', 'Init'],
    toolCount: '31 Gods',
    available: true,
  },
  {
    codename: 'omega-616',
    name: 'Omega',
    godEmoji: '◯',
    godTitle: 'Graceful Shutdown',
    godColor: '#a080d0',
    accentColor: '#c0a0e0',
    description: 'Graceful shutdown. Final state persistence.\nWhen the grid powers down,\nnothing is lost.',
    greekName: 'ΩΜΕΓΑ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Shutdown', 'Final State', 'Graceful Exit'],
    available: true,
  },
  {
    codename: 'iris-616',
    name: 'Iris',
    godEmoji: '🎨',
    godTitle: 'Portal Framework',
    godColor: '#e060c0',
    accentColor: '#ff80e0',
    description: 'Universal portal framework.\nRuns standalone or embedded in Salesforce,\nweb, mobile — any surface.',
    greekName: 'ΙΡΙΣ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Portal', 'React · LWC', 'Any Surface'],
    available: true,
  },
  {
    codename: 'oracle-616',
    name: 'Oracle',
    godEmoji: '🔮',
    godTitle: 'Auth & Identity · OAuth PKCE',
    godColor: '#cc2030',
    accentColor: '#ff4060',
    description: 'Every user passes through Oracle first.\nSalesforce, Google, GitHub, Apple —\nall roads lead to her gates.',
    greekName: 'ΜΑΝΤΕΙΟΝ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Auth · Identity', 'OAuth PKCE', 'SSO'],
    available: true,
  },
  {
    codename: 'hecate-616',
    name: 'Hecate',
    godEmoji: '🔐',
    godTitle: 'Vault & Keys · Ed25519',
    godColor: '#8040c0',
    accentColor: '#a060e0',
    description: 'Cryptographic vault. SSH keys, OAuth tokens,\nAPI keys — one sovereign artifact.\nPrivate keys never leave the device.',
    greekName: 'ΕΚΑΤΗ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Vault · Keys', 'Ed25519', 'Olympus-Coin'],
    available: true,
  },
  {
    codename: 'hestia-616',
    name: 'Hestia',
    godEmoji: '🏠',
    godTitle: 'Config Management',
    godColor: '#f08060',
    accentColor: '#ffa080',
    description: 'Environment configuration,\nsettings management, .env propagation.\nEvery god knows where it stands.',
    greekName: 'ΕΣΤΙΑ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Config Mgmt', 'Settings', 'Environment'],
    available: true,
  },
  {
    codename: 'hephaestus-616',
    name: 'Hephaestus',
    godEmoji: '🔨',
    godTitle: 'Build Tools · Code Exec',
    godColor: '#e08040',
    accentColor: '#ffa060',
    description: 'The build system. Code execution.\nDevelopment tools.\nThe god who makes the things work.',
    greekName: 'ΗΦΑΙΣΤΟΣ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Build Tools', 'Code Exec', 'Forge'],
    available: true,
  },
  {
    codename: 'eos-616',
    name: 'Eos',
    godEmoji: '🌅',
    godTitle: 'CI/CD · Deploy',
    godColor: '#ff8040',
    accentColor: '#ffa060',
    description: 'Push code. Build Docker. Tag SHA.\nPush ECR. Deploy Fargate.\nEvery dawn the grid is newer.',
    greekName: 'ΗΩΣ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['CI/CD', 'Deploy', 'AWS CDK'],
    available: true,
  },
  {
    codename: 'hades-616',
    name: 'Hades',
    godEmoji: '💀',
    godTitle: 'Garbage Collection · DLQ',
    godColor: '#606080',
    accentColor: '#8080a0',
    description: 'Expired tokens. Dead sessions. Stale logs.\nHades runs in the background\nso the grid stays clean.',
    greekName: 'ΑΙΔΗΣ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['GC', 'Log Rotation', 'DLQ Sweep'],
    available: true,
  },
  {
    codename: 'hera-616',
    name: 'Hera',
    godEmoji: '👑',
    godTitle: 'Compliance · Audit',
    godColor: '#d040a0',
    accentColor: '#f060c0',
    description: 'Continuous compliance.\nEvery component operates within\nZeus\'s policies or Hera finds them.',
    greekName: 'ΗΡΑ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Compliance', 'Audit Logs', 'SOC 2'],
    available: true,
  },
  {
    codename: 'delphi-616',
    name: 'Delphi',
    godEmoji: '🌿',
    godTitle: 'Event Bus · Pub/Sub',
    godColor: '#40c0c0',
    accentColor: '#60e0e0',
    description: 'The event bus. Pub/sub messaging.\nAsync communication between every god.\nEverything flows through Delphi.',
    greekName: 'ΔΕΛΦΟΙ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Event Bus', 'Pub/Sub', 'Messaging'],
    available: true,
  },
  {
    codename: 'chronos-616',
    name: 'Chronos',
    godEmoji: '⏱️',
    godTitle: 'BPM Engine · Scheduler',
    godColor: '#c0a060',
    accentColor: '#e0c080',
    description: 'Process automation, scheduled tasks,\nworkflow orchestration.\nTime doesn\'t pass — it executes.',
    greekName: 'ΧΡΟΝΟΣ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['BPM Engine', 'Workflow', 'Scheduler'],
    available: true,
  },
  {
    codename: 'dionysus-616',
    name: 'Dionysus',
    godEmoji: '🎭',
    godTitle: 'Load Testing · Chaos',
    godColor: '#c040e0',
    accentColor: '#e060ff',
    description: 'Load testing, performance benchmarking,\nchaos engineering.\nThrows a party and measures\nhow many guests the grid can handle.',
    greekName: 'ΔΙΟΝΥΣΟΣ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Load Testing', 'Performance', 'Chaos'],
    available: true,
  },
  {
    codename: 'artemis-616',
    name: 'Artemis',
    godEmoji: '🎯',
    godTitle: 'Search & Discovery',
    godColor: '#00c8f0',
    accentColor: '#40e0ff',
    description: 'Search, discover, index.\nEvery piece of data in the grid\nis findable. Artemis hunts through it.',
    greekName: 'ΑΡΤΕΜΙΣ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Search', 'Discovery', 'Indexing'],
    available: true,
  },
  {
    codename: 'orion-616',
    name: 'Orion',
    godEmoji: '⚔️',
    godTitle: 'Async Jobs · Task Queue',
    godColor: '#4090d0',
    accentColor: '#60b0f0',
    description: 'Async job coordination. Task queues.\nBackground work that runs\nwithout blocking the main thread.',
    greekName: 'ΩΡΙΩΝ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Async Jobs', 'Task Queue', 'Orchestration'],
    available: true,
  },
  {
    codename: 'demeter-616',
    name: 'Demeter',
    godEmoji: '🌾',
    godTitle: 'Data Pipelines · Feed Mgmt',
    godColor: '#80c040',
    accentColor: '#a0e060',
    description: 'Sustains the grid. Data pipelines,\nfeed management, keep-alive monitoring.\nNothing starves while she breathes.',
    greekName: 'ΔΗΜΗΤΗΡ',
    shellPrice: '0 shells · infrastructure',
    capabilities: ['Data Feeds', 'Pipelines', 'Keep-Alive'],
    available: true,
  },
]
